### ISSUE TITLE
Are all additional language package folders required?

### ISSUE THREAD

**Issue by al-fisher** [BHoM/CSharp_Toolkit#16]
@adecler as discussed a review is need over the need for the language folders coming from Build folder of CSharp_Toolkit. 

These are naturally captured by installer and make their way to %AppData% folder - so good to clarify needs (or even structure differently/in sub-folder perhaps?!) 

![image](https://user-images.githubusercontent.com/15924573/77742796-f45fe600-700e-11ea-8463-0c29b8cb43a7.png)

**Comment by FraserGreenroyd** [comment]
I second the need for this review as we're doing the referencing changes...! :smile:

**Comment by adecler** [comment]
From initial tests, it looks like we can safely delete them (i.e. not copy them over during post-build).
